name: Bubble--Log Error

on:
  workflow_run:
    workflows:
      - Bubble--Make Preview App
    types: [ completed ]

jobs:
  comment-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: quipper/comment-failure-action@v0.1.1
