name: Remove Peview App

on:
  pull_request:
    types: [closed]

env:
  REPO_NAME: ${{ github.event.repository.name }}
  PR_NUMBER: ${{ github.event.number }}
  # workflow_dispatch:
  #   inputs:
  #     bucket-name:
  #       required: true
  #       type: string
  #     aws-cf-dis-id:
  #       required: true
  #       type: string

      # - name: Missing CloudFront Distribution ID
      #   if: ${{ !inputs.aws-cf-dis-id }}
      #   run: exit 1
      # - name: Missing S3 Bucket name
      #   if: ${{ !inputs.bucket-name }}
      #   run: exit 1

jobs:
  delete:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.BUBBLE_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.BUBBLE_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}
    steps:
      - name: Missing AWS Credentials
        if: ${{ !env.AWS_SECRET_ACCESS_KEY && !env.AWS_ACCESS_KEY_ID }}
        run: exit 1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Retrieve commits
        uses: mathiasvr/command-output@v1
        id: previewappdata
        with:
          run: |
            aws dynamodb get-item --table-name ${{ env.REPO_NAME }}-PreviewApps --key '{ "PullRequestId": {"N": "${{ env.PR_NUMBER }}"}}'
      - name: Parse commits to get AWS Resource IDs
        uses: satackey/action-js-inline@v0.0.2
        id: getresourceids
        with:
          script: |
            const core = require('@actions/core')

            const pullRequestObj = ${{ steps.previewappdata.outputs.stdout }}
            const commitsArray = commitsArray.Item.Commits.L

            const [ buckets, distros, lambdas ] = [[], [], []]

            commitsArray.forEach(commit => {
              const bucketId = commit.M.BucketId.S

              buckets.push(bucketId)
              distros.push(commit.M.CloudFrontDistroId.S)
              lambdas.push(bucketId.split('-')[0])
            });

            core.setOutput('buckets', buckets)
            core.setOutput('distros', distros)
            core.setOutput('lambdas', lambdas)
      - name: Delete all s3 buckets
        run: aws s3 rm s3://${{ inputs.bucket-name }} --recursive
      - name: Delete Cloudfront
        run: |
          sudo apt-get -y install jq
          aws cloudfront get-distribution-config --id ${{ inputs.aws-cf-dis-id }} | jq .DistributionConfig.Enabled=false > tmp.json
          jq -r .DistributionConfig tmp.json > tmp2.json
          aws cloudfront update-distribution --id ${{ inputs.aws-cf-dis-id }} --if-match $(jq .ETag tmp.json -r) --distribution-config file://tmp2.json
          echo q
          aws cloudfront wait distribution-deployed --id ${{ inputs.aws-cf-dis-id }}
          aws cloudfront delete-distribution --id ${{ inputs.aws-cf-dis-id }} --if-match $(aws cloudfront get-distribution-config --id ${{ inputs.aws-cf-dis-id }} | jq .ETag -r)
      - name: Delete Lambdas


