name: Remove All Preview Apps for all Pull Requests in Repo

on:
  workflow_dispatch:
    inputs:
      pr-numbers:
        required: true
        type: string

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      REPO_NAME_WITH_OWNER: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.4
      - name: Execute preview app deletion workflow for each PR number
        run: |
          for PR_NUMBER in ${{ inputs.pr-numbers }}
          do
            gh workflow run delete_PR_preview_apps.yml -f pr-number=$PR_NUMBER --repo ${{ env.REPO_NAME_WITH_OWNER }} -r ${{ steps.branch-name.outputs.current_branch }}
          done
        env:
          GITHUB_TOKEN: ${{ secrets.BUBBLE_GITHUB_TOKEN }}
